POST http://localhost:3000/api/middleman/signup-middleman
Content-Type: application/json

{
    "username":"ParkEase_Bhaktapur",
    "email": "parkeasebhaktapur@gmail.com",
    "password":"parkeasebhaktapur",
    "location":"Bhaktapur"
}